### ISSUE TITLE
Copy link not working on android 10

### ISSUE THREAD

**Issue by thamaraiselvam** [forem/DEV-Android#116]
Copy button on article social sharing not working on android latest Android app. 

1.go to any article
2. click share icon
3. click  copy icon

it's not copied anything.

Android version 10

App version 1.2.1

**Comment by fdoxyz** [comment]
Thanks for the report @thamaraiselvam, it's been a while and we've merged a few PRs related to this since. I think we missed tagging this issue for the automatic close after a PR, sorry for not getting back to this earlier.

We're currently on `1.5.0-2` and I wasn't able to replicate on Android 10. I'm closing now but feel free to reopen if the problem persists at any moment with a bit more details on the device model. Thanks again!
